import { HardwareProfile, PerformanceProfile, Model, Plugin, AuditLog } from "./types";


export const PERFORMANCE_PROFILES: PerformanceProfile[] = [
  {
    id: "eco",
    name: "Eco Profile",
    description: "Ideale per vecchi notebook o mini-PC. Minimizza la temperatura, arresta i processi in background, ed esegue quantizzazioni estreme in RAM compressa.",
    cpuThreadsMultiplier: 0.5,
    batchSize: 1,
    contextWindow: 1024,
    gpuOffloadRatio: 0,
    cachingLevel: "Low",
    ramSwapEnabled: true,
    modelStreaming: true,
    powerLimit: "Sotto-alimentato (Silenzioso)",
  },
  {
    id: "balanced",
    name: "Bilanciato",
    description: "Il profilo standard raccomandato. Bilancia i consumi, mantiene caricate le cache intermedie, e offre un tempo di risposta ottimizzato senza surriscaldare.",
    cpuThreadsMultiplier: 0.75,
    batchSize: 4,
    contextWindow: 2048,
    gpuOffloadRatio: 30,
    cachingLevel: "Medium",
    ramSwapEnabled: false,
    modelStreaming: false,
    powerLimit: "Standard Energetico",
  },
  {
    id: "performance",
    name: "Prestazioni",
    description: "Abilita l'offloading parziale su GPU o l'uso di tutti i core logici disponibili. Mantiene il modello residente in RAM per risposte istantanee.",
    cpuThreadsMultiplier: 1.0,
    batchSize: 8,
    contextWindow: 4096,
    gpuOffloadRatio: 80,
    cachingLevel: "High",
    ramSwapEnabled: false,
    modelStreaming: false,
    powerLimit: "Alte Prestazioni",
  },
  {
    id: "turbo",
    name: "Turbo Overdrive",
    description: "Sfrutta al 100% CPU e GPU. Adatto per lunghe elaborazioni batch, coding assistito complesso e compilazione RAG. I canali termici sono monitorati.",
    cpuThreadsMultiplier: 1.0,
    batchSize: 16,
    contextWindow: 8192,
    gpuOffloadRatio: 100,
    cachingLevel: "Aggressive",
    ramSwapEnabled: false,
    modelStreaming: false,
    powerLimit: "Overdrive Forzato",
  },
  {
    id: "quality",
    name: "Qualità Massima",
    description: "Focalizzato su modelli non-quantizzati o ad altissima fedeltà. Utilizza precisione FP16 e cache estesa, ideale per traduzioni di alta precisione o ragionamento logico.",
    cpuThreadsMultiplier: 0.8,
    batchSize: 2,
    contextWindow: 16384,
    gpuOffloadRatio: 50,
    cachingLevel: "Aggressive",
    ramSwapEnabled: false,
    modelStreaming: false,
    powerLimit: "Bilanciato Dinamico",
  }
];

export const MODEL_CATALOG: Model[] = [
  {
    id: "llama_3_2_3b",
    name: "Llama 3.2 3B",
    category: "Chat",
    size: "1.9 GB",
    quant: "Q4_K_M (GGUF)",
    ramRequired: 4.5,
    vramRequired: 3.5,
    estimatedSpeed: 28,
    description: "Il modello ultraleggero di Meta. Ideale per computer di fascia bassa (8GB RAM), copre chat generali e comprensione base di testi.",
    downloaded: true,
    downloadProgress: 100,
    isDownloading: false,
    rating: 4.8,
    format: "GGUF",
    digitalSignature: "Meta Platforms Inc. Verified",
    sha256: "9f3e4a28bc6e...7d82f10b4",
    version: "v3.2.1"
  },
  {
    id: "deepseek_r1_1_5b",
    name: "DeepSeek-R1 Distill Qwen 1.5B",
    category: "Reasoning",
    size: "1.1 GB",
    quant: "IQ4_XS (GGUF)",
    ramRequired: 3.0,
    vramRequired: 2.2,
    estimatedSpeed: 38,
    description: "Modello di ragionamento logico avanzato distillato. Ottimo per risolvere quesiti complessi e piccoli snippet di codice in pochissima RAM.",
    downloaded: true,
    downloadProgress: 100,
    isDownloading: false,
    rating: 4.9,
    format: "GGUF",
    digitalSignature: "DeepSeek OpenSource Verified",
    sha256: "ac41e54bc810...de415b3e",
    version: "v1.0.0"
  },
  {
    id: "qwen_2_5_coder_1_5b",
    name: "Qwen 2.5 Coder 1.5B",
    category: "Coding",
    size: "1.3 GB",
    quant: "Q5_K_M (GGUF)",
    ramRequired: 3.5,
    vramRequired: 2.8,
    estimatedSpeed: 32,
    description: "Specialista nella generazione di codice e debugging locale. Leggerissimo e ottimizzato per l'integrazione con IDE locali come VS Code.",
    downloaded: false,
    downloadProgress: 0,
    isDownloading: false,
    rating: 4.7,
    format: "GGUF",
    digitalSignature: "Alibaba Cloud Open",
    sha256: "df83a216bce...12a456bd",
    version: "v2.5.2"
  },
  {
    id: "phi_4_reasoning_14b",
    name: "Phi-4 Reasoning 14B",
    category: "Reasoning",
    size: "8.4 GB",
    quant: "IQ3_XS (GGUF)",
    ramRequired: 12.0,
    vramRequired: 8.5,
    estimatedSpeed: 12,
    description: "L'ultimo modello di ragionamento di Microsoft. Richiede hardware medio-alto (16GB RAM o GPU con 8GB VRAM). Perfetto per logica e matematica.",
    downloaded: false,
    downloadProgress: 0,
    isDownloading: false,
    rating: 4.9,
    format: "GGUF",
    digitalSignature: "Microsoft Corp. Signed",
    sha256: "ea821cb91bc...91da82bc",
    version: "v4.0.0"
  },
  {
    id: "mistral_7b_instruct",
    name: "Mistral 7B Instruct v0.3",
    category: "Writing",
    size: "4.1 GB",
    quant: "Q4_K_M (GGUF)",
    ramRequired: 8.0,
    vramRequired: 6.0,
    estimatedSpeed: 18,
    description: "Modello versatile per compiti di scrittura creativa, riassunto testi e marketing. Un grande classico dell'ecosistema Open Source europeo.",
    downloaded: false,
    downloadProgress: 0,
    isDownloading: false,
    rating: 4.6,
    format: "GGUF",
    digitalSignature: "Mistral AI SAS Signed",
    sha256: "72db41bc90a...4bfde810",
    version: "v0.3.0"
  },
  {
    id: "whisper_base_stt",
    name: "Whisper Base Speech-To-Text",
    category: "Audio",
    size: "140 MB",
    quant: "FP16 (ONNX)",
    ramRequired: 1.0,
    vramRequired: 0.5,
    estimatedSpeed: 150, // words/min
    description: "Trascrizione audio multilingue locale superveloce. Funziona in millisecondi anche su vecchi iMac Intel.",
    downloaded: true,
    downloadProgress: 100,
    isDownloading: false,
    rating: 4.9,
    format: "ONNX",
    digitalSignature: "OpenAI OpenSource Release",
    sha256: "ab21cd83ef2...fc812bc3",
    version: "v1.1.0"
  },
  {
    id: "stable_diffusion_tiny",
    name: "TinySD (Stable Diffusion)",
    category: "ImageGen",
    size: "820 MB",
    quant: "INT8 (ONNX)",
    ramRequired: 4.0,
    vramRequired: 3.0,
    estimatedSpeed: 5, // sec/image
    description: "Generatore locale di immagini ultra-ottimizzato. Produce immagini 512x512 pixel in pochi secondi su hardware entry-level.",
    downloaded: false,
    downloadProgress: 0,
    isDownloading: false,
    rating: 4.5,
    format: "ONNX",
    digitalSignature: "CompVis Group Verified",
    sha256: "bc5672dfbc3...a82bce45",
    version: "v1.0.1"
  }
];

export const PLUGINS_LIST: Plugin[] = [
  {
    id: "vs_code_integration",
    name: "Integrazione VS Code (Copilot)",
    author: "AI Hub Community Team",
    version: "1.4.2",
    description: "Espone un'API locale compatibile con OpenAI (localhost:3000/v1) per alimentare estensioni di autocomplete codice su VS Code, Cursor e VSCodium.",
    category: "Integration",
    installed: true,
    rating: 4.9,
    signed: true
  },
  {
    id: "rag_pdf_analyzer",
    name: "Document QA & RAG Engine",
    author: "RAG Community Devs",
    version: "2.1.0",
    description: "Inietta documenti PDF, TXT o file Office in un database vettoriale locale SQLite-Vec per fare domande e ricevere risposte precise basate sul contesto.",
    category: "RAG",
    installed: true,
    rating: 4.8,
    signed: true
  },
  {
    id: "whisper_voice_assistant",
    name: "Controllo Vocale & STT",
    author: "VoiceLab Open",
    version: "0.9.5",
    description: "Abilita il controllo dell'interfaccia dell'app con la voce e trascrive interviste/note audio importando file direttamente sul disco.",
    category: "UIs",
    installed: false,
    rating: 4.4,
    signed: false
  },
  {
    id: "obsidian_sync",
    name: "Obsidian Local Sync",
    author: "KnowledgeBase Foundation",
    version: "1.0.1",
    description: "Sincronizza automaticamente le risposte e le sintesi create dall'AI Hub direttamente nelle tue cartelle di note Obsidian (.md).",
    category: "Storage",
    installed: false,
    rating: 4.6,
    signed: true
  }
];

export const SECURITY_LOGS: AuditLog[] = [
  {
    id: "log_1",
    timestamp: "15:32:10",
    type: "Security",
    action: "Verifica firma SHA256 modello 'Llama 3.2 3B'",
    status: "Success"
  },
  {
    id: "log_2",
    timestamp: "15:32:11",
    type: "Privacy",
    action: "Inizializzazione sandbox completata",
    status: "Success"
  },
  {
    id: "log_3",
    timestamp: "15:34:00",
    type: "System",
    action: "Cambio profilo energetico: Eco Mode attivato",
    status: "Success"
  },
  {
    id: "log_4",
    timestamp: "15:35:12",
    type: "Security",
    action: "Esecuzione plugin 'VS Code Integration' in sandbox locale",
    status: "Success"
  },
  {
    id: "log_5",
    timestamp: "15:36:01",
    type: "Privacy",
    action: "Connessione internet disabilitata (Esecuzione offline al 100%)",
    status: "Success"
  }
];
